language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

notifications:
    email: false

before_install:
    - pip install pep8
    - pip install misspellings

script:
    # Run pep8 on all .py files in all subfolders
    - find . -name \*.py -exec pep8 --ignore=E501,E402 {} +
    - find . -name '*.py' | misspellings -f -

#deploy:
#  provider: pypi
#  user: "karimb"
#  password: "Your password"
